// src/components/Weather/Weather.tsx
import React, { useState, useCallback } from "react";
import {
  Box,
  Card,
  CardContent,
  Grid,
  Slider,
  Switch,
  FormControlLabel,
  Button,
  Typography,
  Fade,
  styled,
  ButtonBase,
} from "@mui/material";
import { useDigitalTwinApi } from "@/hooks/useDigitalTwinApi";
import { WeatherOptions } from "@/utils/weatherUtils";

let sunnyIcon = "/assets/weather/Sunny.png";
let cloudyIcon = "/assets/weather/Cloudy.png";
let rainIcon = "/assets/weather/Rain.png";
let snowIcon = "/assets/weather/Snow.png";

const WeatherContainer = styled(Box)({
  position: "absolute",
  top: "80px",
  right: "40px",
  padding: "10px",
  borderRadius: "2%",
  zIndex: 10,
  background: "rgba(0, 0, 0, 0.331)",
  fontFamily: "Tencent, Arial, sans-serif",
});

const WeatherCard = styled(Card)({
  backgroundColor: "transparent",
  boxShadow: "none",
});

const WeatherGrid = styled(Box)({
  display: "grid",
  gridTemplateRows: "2fr 1fr 1fr",
  gap: "10px",
});

const WeatherItemsContainer = styled(Box)({
  display: "flex",
  marginBottom: "10px",
  whiteSpace: "nowrap",
});

const WeatherItem = styled(ButtonBase)({
  display: "flex",
  flexDirection: "column",
  justifyContent: "center",
  alignItems: "center",
  padding: "10px 15px",
  cursor: "pointer",
  borderRadius: "8px",
  transition: "background-color 0.2s",
  "&:hover": {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
  },
});

const WeatherIcon = styled("img")({
  width: "30px",
  height: "30px",
});

const WeatherText = styled(Typography)({
  color: "rgba(255, 255, 255, 0.8)",
  fontSize: "14px",
  marginTop: "5px",
});

const SliderContainer = styled(Box)({
  display: "flex",
  alignItems: "center",
  height: "30px",
  padding: "0 25px 0 15px",
});

const TimeDisplay = styled(Typography)({
  color: "#fff",
  width: "40px",
  fontSize: "14px",
});

const StyledSlider = styled(Slider)({
  width: "160px",
  marginLeft: "10px",
  color: "#66ddff",
  "& .MuiSlider-track": {
    background: "linear-gradient(90deg, #66ddff, #409eff)",
    animation: "liuguang 2s infinite linear",
  },
  "& .MuiSlider-rail": {
    backgroundColor: "rgba(0, 0, 0, 0.258)",
  },
  "& .MuiSlider-thumb": {
    width: "15px",
    height: "15px",
    background: "radial-gradient(rgba(102, 221, 255, 0.9), rgba(0, 0, 0, 0.8))",
    border: "2px solid rgb(102, 221, 255)",
  },
});

const ControlsContainer = styled(Box)({
  display: "flex",
  alignItems: "center",
  justifyContent: "space-between",
});

const DarkModeContainer = styled(Box)({
  display: "flex",
  alignItems: "center",
  fontSize: "16px",
  padding: "0 25px 0 12px",
});

const ResetButton = styled(Button)({
  fontSize: "16px",
  marginTop: "8px",
  marginLeft: "10px",
  border: "1px solid #fff",
  borderRadius: "5px",
  color: "rgba(255, 255, 255, 0.8)",
  padding: "3px 5px",
  minWidth: "auto",
  "&:hover": {
    color: "#409eff",
    borderColor: "#409eff",
  },
});

export interface WeatherItem {
  name: string;
  icon: string;
  options: WeatherOptions;
}

const weatherItems: WeatherItem[] = [
  {
    name: "Sunny",
    icon: sunnyIcon,
    options: {
      cloudDensity: 0.1,
      SunIntensity: 15,
    },
  },
  {
    name: "Cloudy",
    icon: cloudyIcon,
    options: {
      cloudDensity: 0.8,
      SunIntensity: 7,
    },
  },
  {
    name: "Rain",
    icon: rainIcon,
    options: {
      cloudDensity: 0.8,
      sunIntensity: 8,
      rainParam: [0.2, 0.2, 0.2, "White", 0.2, 0.05],
    },
  },
  {
    name: "Snow",
    icon: snowIcon,
    options: {
      cloudDensity: 0.8,
      sunIntensity: 8,
      snowParam: [0.2, 0.2, 0.2, "White", 0.2, 0.05],
    },
  },
];

export const Weather: React.FC = () => {
  const [currentTime, setCurrentTime] = useState(8 * 60 * 60 + 53 * 60); // 8:53 AM in seconds
  const [isDark, setIsDark] = useState(false);

  // Use the consolidated hook methods instead of duplicating logic
  const { resetPlayer, setDarkMode, setWeatherTime, updateWeather } =
    useDigitalTwinApi();

  const sliderFormat = useCallback((time: number): string => {
    const [hour, minute] = getHourMinute(time);
    return `${hour}:${minute}`;
  }, []);

  const getHourMinute = useCallback((time: number): [string, string] => {
    const [hourStr, fraction] = (time / 60 / 60).toFixed(2).split(".");
    const hour = hourStr;
    const minutes = Math.floor(Number("0." + fraction) * 60)
      .toString()
      .padStart(2, "0");
    return [hour, minutes];
  }, []);

  const handleTimeSliderChange = useCallback(
    async (event: Event, value: number | number[]) => {
      const time = Array.isArray(value) ? value[0] : value;
      setCurrentTime(time);

      try {
        const [hour, minute] = getHourMinute(time);
        await setWeatherTime(Number(hour), Number(minute));
      } catch (error) {
        console.error("Error setting time:", error);
      }
    },
    [getHourMinute, setWeatherTime]
  );

  const handleDarkModeChange = useCallback(
    async (event: React.ChangeEvent<HTMLInputElement>) => {
      const newIsDark = event.target.checked;
      setIsDark(newIsDark);

      try {
        await setDarkMode(newIsDark);
      } catch (error) {
        console.error("Error setting dark mode:", error);
      }
    },
    [setDarkMode]
  );

  const handleWeatherInit = useCallback(async () => {
    try {
      // Reset player with weather and environment flags (2 | 4 = 6)
      await resetPlayer(6);
      setIsDark(false);
      setCurrentTime(8 * 60 * 60 + 53 * 60); // Reset to 8:53 AM
    } catch (error) {
      console.error("Error resetting weather:", error);
    }
  }, [resetPlayer]);

  const handleWeatherChange = useCallback(
    async (options: WeatherOptions) => {
      try {
        await updateWeather(options);
      } catch (error) {
        console.error("Error changing weather:", error);
      }
    },
    [updateWeather]
  );

  return (
    <Fade in={true} timeout={1000} style={{ transitionDelay: "300ms" }}>
      <WeatherContainer>
        <WeatherCard>
          <CardContent sx={{ p: 0 }}>
            <WeatherGrid>
              {/* Weather Items */}
              <WeatherItemsContainer>
                {weatherItems.map((item, index) => (
                  <WeatherItem
                    key={index}
                    onClick={() => handleWeatherChange(item.options)}
                  >
                    <WeatherIcon src={item.icon} alt={item.name} />
                    <WeatherText>{item.name}</WeatherText>
                  </WeatherItem>
                ))}
              </WeatherItemsContainer>

              {/* Time Slider */}
              <SliderContainer>
                <TimeDisplay>{sliderFormat(currentTime)}</TimeDisplay>
                <StyledSlider
                  value={currentTime}
                  onChange={handleTimeSliderChange}
                  min={1}
                  max={86380}
                  step={60 * 10} // 10-minute steps
                />
              </SliderContainer>

              {/* Controls */}
              <ControlsContainer>
                <DarkModeContainer>
                  <FormControlLabel
                    control={
                      <Switch
                        checked={isDark}
                        onChange={handleDarkModeChange}
                        sx={{
                          "& .MuiSwitch-switchBase.Mui-checked": {
                            color: "#0c0c0c",
                          },
                          "& .MuiSwitch-switchBase.Mui-checked + .MuiSwitch-track":
                            {
                              backgroundColor: "#0c0c0c",
                            },
                          "& .MuiSwitch-track": {
                            backgroundColor: "#ccc",
                          },
                        }}
                      />
                    }
                    label={
                      <Typography
                        sx={{
                          color: "rgba(255, 255, 255, 0.8)",
                          fontSize: "16px",
                        }}
                      >
                        Toggle Scene Lighting:
                      </Typography>
                    }
                    labelPlacement="start"
                  />
                </DarkModeContainer>

                <ResetButton onClick={handleWeatherInit}>Reset</ResetButton>
              </ControlsContainer>
            </WeatherGrid>
          </CardContent>
        </WeatherCard>
      </WeatherContainer>
    </Fade>
  );
};

// src/components/weather/index.vue
<template>
    <transition
      appear
      name="custom-classes-transition"
      enter-active-class="animate__animated animate__faster animate__fadeInDown"
      leave-active-class="animate__animated animate__faster animate__fadeOutUp"
    >
      <div class="weather">
        <div class="set-box">
          <div class="weather-items">
            <div
              class="item"
              v-for="(item, index) in weatherItems"
              :key="index"
              @click="setWeather(item.options)"
            >
              <img class="img" :src="item.icon" alt="" />
              <span class="text">{{ item.name }}</span>
            </div>
          </div>
          <div class="slider__content">
            <div class="slider--time">{{ sliderFormat(currentTime) }}</div>
            <el-slider
              v-model="currentTime"
              :max="86380"
              :min="1"
              :step="60 * 10"
              :show-tooltip="false"
              class="elSlider"
              @change="changeTimeSilde"
            />
          </div>
          <div class="flex">
            <div class="open-dark">
              <div class="dark-item">
                <span>Toggle Scene Lighting:</span>
                <el-switch
                  v-model="isDark"
                  @change="changeDarkMode"
                  class="ml-2"
                  style="--el-switch-on-color: #0c0c0c; --el-switch-off-color: #ccc"
                />
              </div>
            </div>
            <div class="init"><span @click="weatherInit">Reset</span></div>
          </div>
        </div>
      </div>
    </transition>
  </template>
  
  <script setup lang="ts">
  import { ref } from 'vue'
  import { changeWeather } from './methods/changeWeather'
  import sunnyIcon from './img/Sunny.png'
import cloudyIcon from './img/Cloudy.png'
import rainIcon from './img/Rain.png'
import snowIcon from './img/Snow.png'
  const currentTime = ref(8 * 60 * 60 + 53 * 60)
  const isDark = ref(false)
  
  const weatherItems = [
    {
      name: 'Sunny',
      icon: sunnyIcon,
      options: {
        cloudDensity: 0.1,
        SunIntensity: 15,
      },
    },
    {
      name: 'Cloudy',
      icon: cloudyIcon,
      options: {
        cloudDensity: 0.8,
        cloudParam: [[0.6, 0.6, 0.6, 1], 3],
        lowCloud: [0.7, 0.5, 0.2, 5, 0],
        SunIntensity: 7,
      },
    },
    {
      name: 'Rain',
      icon: rainIcon,
      options: {
        cloudDensity: 0.8,
        cloudParam: [[0.6, 0.6, 0.6, 1], 3],
        lowCloud: [0.7, 0.5, 0.2, 5, 0],
        sunIntensity: 8,
        rainParam: [0.2, 0.2, 0.2, null, 0.2, 0.05],
      },
    },
    {
      name: 'Snow',
      icon: snowIcon,
      options: {
        cloudDensity: 0.8,
        cloudParam: [[0.6, 0.6, 0.6, 1], 3],
        lowCloud: [0.7, 0.5, 0.2, 5, 0],
        sunIntensity: 8,
        snowParam: [0.2, 0.2, 0.2, null, 0.2, 0.05],
      },
    },
  ]
  
  function setWeather(options: any) {
    changeWeather(options)
  }
  
  function sliderFormat(time: number): string {
    const [hour, minute] = getHourMinute(time)
    return `${hour}:${minute}`
  }
  
  function changeTimeSilde(time: number) {
    const [hour, minute] = getHourMinute(time)
    fdapi.weather.setDateTime(null, null, null, Number(hour), Number(minute))
  }
  
  function getHourMinute(time: number): [string, string] {
    const [hourStr, fraction] = (time / 60 / 60).toFixed(2).split('.')
    const hour = hourStr
    const minutes = Math.floor(Number('0.' + fraction) * 60)
      .toString()
      .padStart(2, '0')
    return [hour, minutes]
  }
  
  function changeDarkMode(flag: boolean) {
    fdapi.weather.setDarkMode(flag)
  }
  
  function weatherInit() {
    fdapi.reset(2 | 4)
    isDark.value = false
    currentTime.value = 8 * 60 * 60 + 53 * 60
  }
  </script>
  <style lang="scss" scoped>
  .weather {
      position: absolute;
      // @include Width(260);
      @include Top(80);
      @include Right(40);
      @include Padding(10, 10, 10, 10);
      border-radius: 2%;
      margin: auto;
      overflow-y: auto;
      // overflow-x: hidden;
      z-index: 10;
      background: rgba(0, 0, 0, 0.331);
          font-family: Tencent;
      .set-box {
          display: grid;
          grid-template-rows: 2fr 1fr 1fr;
          .weather-items {
              display: flex;
              @include MarginBottom(10);
              white-space: nowrap;
              .item {
                  display: flex;
                  flex-direction: column;
                  justify-content: center;
                  align-items: center;
                  @include Padding(10, 15, 10, 15);
                  cursor: pointer;
          
                  .img {
                      @include Width(30);
                      @include wHeight(30);
                  }
          
                  .text {
                      color: rgba($color: #ffffff, $alpha: 0.8);
                      @include FontSize(14);
                      @include MarginTop(5);
                  }
              }
          }
          .slider__content {
              display: flex;
              align-items: center;
              @include wHeight(30);
              @include Padding(0, 25, 0, 15);
  
              .slider--time {
                  color: #fff;
                  @include Width(40);
                  @include FontSize(14);
              }
  
              .elSlider {
                  @include Width(160);
                  @include MarginLeft(10);
                  border-radius: 50%;
  
                  ::v-deep(.el-slider__bar) {
                      animation: liuguang 2s infinite linear;
                  }
  
                  ::v-deep(.el-slider__runway) {
                      background-color: rgba(0, 0, 0, 0.258);
                  }
  
                  ::v-deep(.el-slider__button) {
                      @include Width(15);
                      @include wHeight(15);
                      @include MarginLeft(8);
                      border-color: rgb(102, 221, 255);
                      background: radial-gradient(rgba(102, 221, 255, 0.9), rgba(0, 0, 0, 0.8));
                  }
              }
          }
          .flex {
              display: flex;
              .open-dark {
                  display: flex;
                  justify-content: space-between;
                  @include FontSize(16);
                  @include Padding(0, 25, 0, 12);
          
                  .dark-item {
                      display: flex;
                      align-items: center;
                  }
          
                  span {
                      color: rgba($color: #ffffff, $alpha: 0.8);
                      @include MarginRight(10);
                  }
              }
          
              .init {
                  cursor: pointer;
                  @include FontSize(16);
                  @include MarginTop(8);
                  @include MarginLeft(10);
          
                  span {
                      border: 1px solid #fff;
                      border-radius: 5px;
                      color: rgba($color: #ffffff, $alpha: 0.8);
                      @include Padding(3, 5, 3, 5);
          
                      &:hover {
                          color: #409eff;
                      }
                  }
              }
          }
      }
  }
  </style>
