// src/components/RouterNav/RouterNav.tsx
import React, { useState, useEffect } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { Box, ButtonBase, Typography, Fade, styled } from "@mui/material";

// set default and active images
let img1Default = "/assets/images/link/1级菜单_icon1_默认.png";
let img1Active = "/assets/images/link/1级菜单_icon1_选中.png";
let img3Default = "/assets/images/link/1级菜单_icon3_默认.png";
let img3Active = "/assets/images/link/1级菜单_icon3_选中.png";
let img5Default = "/assets/images/link/1级菜单_icon5_默认.png";
let img5Active = "/assets/images/link/1级菜单_icon5_选中.png";

const NavigationContainer = styled(Box)({
  position: "absolute",
  bottom: "40px",
  width: "700px",
  left: "50%",
  transform: "translateX(-50%)",
  zIndex: 10,
  height: "102px",
});

const NavigationLinks = styled(Box)({
  position: "absolute",
  left: "50%",
  transform: "translateX(-50%)",
  bottom: 0,
  top: "120px",
  margin: "auto",
  zIndex: 10,
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
});

const NavigationButton = styled(ButtonBase)<{ active?: boolean }>(
  ({ active }) => ({
    width: "152px",
    height: "38px",
    margin: "0 27px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    position: "relative",
    fontSize: "18px",
    transition: "all 0.5s",
    color: active ? "#ffffff" : "rgba(255, 255, 255, 0.8)",
    letterSpacing: active ? "1px" : "0px",
    "&:hover": {
      color: "#ffffff",
      transform: "scale(1.05)",
    },
  })
);

const NavigationImage = styled("img")({
  width: "130px",
  position: "absolute",
  transform: "translate(0, -90%)",
  transition: "all 0.3s",
});

const NavigationText = styled(Typography)({
  position: "absolute",
  bottom: "55px",
  width: "130px",
  height: "40px",
  fontSize: "18px",
  letterSpacing: "5px",
  fontFamily: "Oppo, serif",
  color: "rgba(255, 255, 255, 0.8)",
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
});

interface NavigationItem {
  name: string;
  key: number;
  path: string;
  icon: string;
  img: string;
  activeImg: string;
}

const navigationItems: NavigationItem[] = [
  {
    name: "Module1",
    key: 1,
    path: "/home/page1", // Match the nested route structure
    icon: "icon1",
    img: img1Default,
    activeImg: img1Active,
  },
  {
    name: "Module2",
    key: 2,
    path: "/home/page2", // Match the nested route structure
    icon: "icon3",
    img: img3Default,
    activeImg: img3Active,
  },
  {
    name: "Module3",
    key: 3,
    path: "/home/page3", // Match the nested route structure
    icon: "icon5",
    img: img5Default,
    activeImg: img5Active,
  },
];

const RouterNav: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const [currentPath, setCurrentPath] = useState("");

  useEffect(() => {
    setCurrentPath(location.pathname);
  }, [location.pathname]);

  const handleNavigation = (item: NavigationItem) => {
    navigate(item.path);
    setCurrentPath(item.path);
  };

  // Check if current path matches the navigation item path
  const isActive = (path: string) => location.pathname === path;

  return (
    <Fade in timeout={1000}>
      <NavigationContainer>
        <NavigationLinks>
          {navigationItems.map((item) => (
            <NavigationButton
              key={item.key}
              active={isActive(item.path)}
              onClick={() => handleNavigation(item)}
            >
              <Box
                sx={{
                  width: "152px",
                  position: "relative",
                  height: "100%",
                  display: "flex",
                  justifyContent: "center",
                }}
              >
                <Fade in={isActive(item.path)} timeout={300}>
                  <NavigationImage
                    src={item.activeImg}
                    alt={item.name}
                    style={{ display: isActive(item.path) ? "block" : "none" }}
                  />
                </Fade>
                <Fade in={!isActive(item.path)} timeout={300}>
                  <NavigationImage
                    src={item.img}
                    alt={item.name}
                    style={{ display: !isActive(item.path) ? "block" : "none" }}
                  />
                </Fade>
              </Box>
              <NavigationText>{item.name}</NavigationText>
            </NavigationButton>
          ))}
        </NavigationLinks>
      </NavigationContainer>
    </Fade>
  );
};

export default RouterNav;

// src/components/routerNav/index.vue
<template>
    <transition appear name="custom-classes-transition" enter-active-class="animate__animated   animate__fadeInUp"
        leave-active-class="animate__animated  animate__fadeOutDown">
        <div class="footer">
            <div class="footer_link">
                <div @click="LinkClick(item)" :class="PagePath.indexOf(item.path) !== -1 ? 'link isactive' : 'link'"
                    v-for="item in Link" :key="item.key">
                    <div class="link-img">
                        <transition appear name="custom-classes-transition"
                            enter-active-class="animate__animated    animate__fadeIn"
                            leave-active-class="animate__animated   animate__fadeOut">
                            <img :src="item.activeImg" alt="" v-if="PagePath.indexOf(item.path) !== -1" />
                        </transition>
                        <transition appear name="custom-classes-transition"
                            enter-active-class="animate__animated    animate__fadeIn"
                            leave-active-class="animate__animated   animate__fadeOut">
                            <img :src="item.img" alt="" v-if="PagePath.indexOf(item.path) === -1" />
                        </transition>
                    </div>
                    <div class="link_name">
                        <span>
                            {{ item.name }}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </transition>
</template>

<script lang="ts" setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { onBeforeRouteUpdate, useRoute, useRouter } from 'vue-router'
import img1Default from '@/assets/images/link/1级菜单_icon3_默认.png'
import img1Active from '@/assets/images/link/1级菜单_icon3_选中.png'
import img2Default from '@/assets/images/link/1级菜单_icon5_默认.png'
import img2Active from '@/assets/images/link/1级菜单_icon5_选中.png'
import img3Default from '@/assets/images/link/1级菜单_icon1_默认.png'
import img3Active from '@/assets/images/link/1级菜单_icon1_选中.png'
// 路由监听
onBeforeRouteUpdate(to => {
  PagePath.value = to.path
})

// 路由信息
const Link = reactive([
  {
    name: 'Module1',
    key: 1,
    path: '/home/page1',
    icon: 'jianceyujing',
    img: img1Default,
    activeImg: img1Active
  },
  {
    name: 'Module2',
    key: 2,
    path: '/home/page2',
    icon: 'rengongzhinengdanao',
    img: img2Default,
    activeImg: img2Active
  },
  {
    name: 'Module3',
    key: 3,
    path: '/home/page3',
    icon: 'rengongzhinengdanao',
    img: img3Default,
    activeImg: img3Active
  }
])
const Router = useRouter()
const Route = useRoute()
const PagePath = ref('')
// 一级路由点击
const LinkClick = (val: { name: string; key: number; path: string; icon: string }) => {
  Router.push({
    path: val.path
  })
  PagePath.value = val.path
}
const rain: any = ref([])
const link_icon = ref()
onMounted(() => {
  PagePath.value = Route.path
})
</script>

<style lang="scss" scoped>
.footer {
    position: absolute;
    @include Bottom(40);
    @include Width(700);
    left: 0;

    right: 0;
    margin: auto;
    z-index: 10;
    @include wHeight(102);

    .footer_link {
        position: absolute;
        left: 0;
        right: 0;
        bottom: 0;
        // top: 0;
        @include Top(120);
        margin: auto;
        z-index: 10;
        display: flex;
        justify-content: center;
        align-items: center;

        .link {
            @include Width(152);
            @include wHeight(38);
            @include Margin(0, 27, 0, 27);
            display: flex;
            justify-content: center;
            align-items: center;
            position: relative;
            cursor: pointer;
            @include FontSize(18);
            transition: all 0.5s;

            .link-img {
                @include Width(152);
                position: relative;
                transition: all 0.3s;
                height: 100%;
                display: flex;
                justify-content: center;

                img {
                    // @include wHeight(82);

                    @include Width(130);
                    transition: all 0.3s;
                    position: absolute;
                    transform: translate(0, -90%);
                }
            }

            &.isactive {
                background-size: 100% 100%;
                color: #ffffff;
                @include LetterSpacing(1);
            }

            &.link::before {
                content: '';
                position: absolute;
                @include Width(22);
                @include wHeight(22);
                //background: url("~@/assets/images/基础/header/point@2x.png") no-repeat center/cover;
                @include Left(-37);
            }

            &.link:nth-of-type(1)::before {
                content: '';
                position: absolute;
                @include Width(94);
                @include wHeight(10);
                //background: url("~@/assets/images/基础/header/menuleft@2x.png") no-repeat center/cover;
                @include Left(-94);
            }

            &.link:last-child::after {
                content: '';
                position: absolute;
                @include Width(94);
                @include wHeight(10);
                //background: url("~@/assets/images/基础/header/menuright@2x.png") no-repeat center/cover;
                // @include Left(94);
                left: 100%;
            }

            .link_name {
                position: absolute;
                @include Bottom(55);
                @include Width(130);
                @include wHeight(40);
                @include FontSize(18);
                @include LetterSpacing(5);
                font-family: Oppo, serif;
                color: rgba($color: #ffffff, $alpha: 0.8);

                left: 0;
                right: 0;
                margin: auto;
                @include MarginTop(10);
                display: flex;
                justify-content: center;
                align-items: center;
            }

            .toplinks {
                position: fixed;
                @include Bottom(105);
                left: 0;
                right: 0;
                margin: auto;
                @include Width(800);
                @include wHeight(40);
                display: flex;
                justify-content: center;
                align-items: center;
                z-index: 10;

                .toplink {
                    @include Width(140);
                    @include wHeight(40);
                    @include Margin(0, 20, 0, 20);
                    @include FontSize(18);
                    color: #ffffff98;
                    display: flex;
                    font-family: Oppo;

                    justify-content: center;
                    align-items: center;

                    background-size: 100% 100%;

                    &.toplink_active {
                        //background: url("~@/assets/images/基础/header/btn_当前选中@2x.png") no-repeat center/cover;
                        background-size: 100% 100%;
                        color: #98deff;

                        .svg_left {
                            // font-size: 3000px;
                            color: #ffffff;
                            transform: scale(5);
                        }
                    }
                }
            }
        }
    }

    .link_icon {
        position: absolute;
        @include Width(36);
        @include wHeight(38);
        @include Bottom(-19);
        @include CalcLeft(v-bind(Key));
        transition: left 0.5s;

        img {
            width: 100%;
        }
    }
}
</style>
